# Generated by Django 3.0.4 on 2020-03-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('been_and_mark', '0002_auto_20200322_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ImageField(default='no_name.png', upload_to='place_pictures'),
        ),
    ]
